In [1]:
# Auto-reload magic to ease developments of modules
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt
import numpy as np

from utils.datasets import make_linear
from models.linear_model import ClosedFormLinearRegression, GradientDescentLinearRegression

In [3]:
X, y, weights= make_linear(samples=50, features=3, random_seed=42)

In [4]:
weights

array([12.87877587, -4.86063712, -2.7034397 , -3.68177782])

In [5]:
lr_inv = ClosedFormLinearRegression(method='inverse')
%time lr_inv.fit(X,y)
lr_inv.weights

Wall time: 11.6 ms


array([13.13522167, -4.94001704, -2.68080441, -3.77224678])

In [6]:
lr_pinv = ClosedFormLinearRegression(method='pseudoinverse')
%time lr_pinv.fit(X,y)
lr_pinv.weights

Wall time: 3 ms


array([13.13522167, -4.94001704, -2.68080441, -3.77224678])

In [7]:
#batch gradient descent not converging
gd = GradientDescentLinearRegression(batch_size="full",learning_rate=0.1)
%time gd.fit(X,y)
gd.weights

Wall time: 354 ms
c:\Users\OPC\Documents\GitHub\fromscratchml\models\linear_model.py:149: UserWarning: Max numbers of iterations has been reached
  warnings.warn("Max numbers of iterations has been reached")


array([nan, nan, nan, nan])

In [8]:
#batch gradient descent
gd = GradientDescentLinearRegression(batch_size="full",learning_rate=0.01)
%time gd.fit(X,y)
gd.weights

Wall time: 19 ms


array([13.13471   , -4.94001142, -2.68081715, -3.77224059])

In [9]:
#stochastic gradient descent
gd = GradientDescentLinearRegression(batch_size=1,learning_rate=0.0005)
%time gd.fit(X,y)
gd.weights

Wall time: 1.29 s
c:\Users\OPC\Documents\GitHub\fromscratchml\models\linear_model.py:149: UserWarning: Max numbers of iterations has been reached
  warnings.warn("Max numbers of iterations has been reached")


array([13.07357491, -4.97799812, -2.69123575, -3.5551437 ])

In [10]:
#minibatch gradient descent v1
gd = GradientDescentLinearRegression(batch_size=0.5,learning_rate=0.001)
%time gd.fit(X,y)
gd.weights

Wall time: 1.39 s
c:\Users\OPC\Documents\GitHub\fromscratchml\models\linear_model.py:149: UserWarning: Max numbers of iterations has been reached
  warnings.warn("Max numbers of iterations has been reached")


array([13.15050351, -4.90713916, -2.69410261, -3.76353885])